openapi: 3.1.0
info:
  title: Your API Title
  description: Description of your API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /your/path/here:
    get:
      summary: Summary of the endpoint
      description: Detailed description of the endpoint
      responses:
        '200':
          description: Successful response
        '404':
          description: Resource not found
components:
  schemas:
    YourSchemaName:
      type: object
      properties:
        propertyName:
          type: string
      required:
        - propertyName

